Intentional error in CI pipeline

diff --git a/.github/workflows/workflow1.yml b/.github/workflows/workflow1.yml
--- a/.github/workflows/workflow1.yml
+++ b/.github/workflows/workflow1.yml
@@ -17,5 +17,8 @@ jobs:
     steps:
       # Check-out your repository
       - uses: actions/checkout@v3
+
+      - name: To Show Erroe
+        run: echo "Should fail at this point"; exit 1
       - name: Run a one-line script
         run: echo "Continuous Integration"
